apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants-environments
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - tenant: tenant-sass-common
                # - tenant: tenant1
                # - tenant: tenant2
                - tenant: tenant3
          - clusters: {}
              # selector:
              #   matchLabels:
              #     environment: control-plane
  template:
    metadata:
      name: '{{.tenant}}-{{.name}}'  # Use tenant and cluster name for uniqueness
    spec:
      project: default
      source:
        repoURL: '{{.metadata.annotations.addons_repo_url}}'
        targetRevision: '{{.metadata.annotations.addons_repo_revision}}'
        path: 'gitops/tenants/{{.tenant}}'
      destination:
        name: '{{.name}}'
        namespace: default
      syncPolicy:
        retry:
          limit: 10
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
