apiVersion: sql.azure.upbound.io/v1beta2
kind: MSSQLDatabase
metadata:
  name: sqldb-tenark-sass-tenant2
spec:
  forProvider:
    collation: SQL_Latin1_General_CP1_CI_AS
    enclaveType: VBS
    licenseType: LicenseIncluded
    maxSizeGb: 1
    readScale: true
    serverIdRef:
      name: sql-tenark-sass-tenant-common
    skuName: S0
    tags:
      tenant: tenant2
    zoneRedundant: true