apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant2-vcluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    clusterName: tenant2
spec:
  project: default
  sources:
    # - path: environments/env-green/ingress
    #   repoURL: https://github.com/leunamnauj/Engineering-Multi-Tenancy-for-Crossplane-Automating-Environments-with-vClusters-and-GitOps.git
    #   targetRevision: HEAD
    - repoURL: https://charts.loft.sh
      targetRevision: 0.22.0
      chart: vcluster
      helm:
        releaseName: tenant2
        values: |
          pro: false
          exportKubeConfig:
            context: tenant2
            server: https://tenant2.tenark.com:32443
            secret:
              name: tenant2-ext
              namespace: tenant2
          sync:
            toHost:
              ingresses:
                enabled: true
          controlPlane:
            distro:
              k3s:
                enabled: true
            proxy:
              extraSANs:
              - tenant2
              - tenant2.tenant2
              - tenant2.tenant2.svc
              - tenant2.tenant2.svc.cluster.local
            statefulSet:
              scheduling:
                podManagementPolicy: OrderedReady
                    
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true