apiVersion: sql.azure.upbound.io/v1beta2
kind: MSSQLDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1beta2/mssqldatabase
  labels:
    testing.upbound.io/example-name: example5
  name: example5
spec:
  forProvider:
    collation: SQL_Latin1_General_CP1_CI_AS
    licenseType: LicenseIncluded
    maxSizeGb: 1
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: mssqlelasticpoolsrv
    skuName: S0
    tags:
      foo: bar