apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - resource-group.yaml
  - sql-admin-password.yaml
  - sql-database.yaml
  - sql-server.yaml
  - vcluster.yaml