---
apiVersion: batch/v1
kind: Job
metadata:
  name: kubeconfig-generator
  annotations:
    uptest.upbound.io/timeout: "60"
spec:
  template:
    spec:
      serviceAccountName: vcluster-admin
      containers:
      - name: kubeconfig-generator
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          CA_CERT=$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt | base64 -w 0)
          APISERVER=https://kubernetes.default.svc
          NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          JOB_UID=$(kubectl get job kubeconfig-generator -o jsonpath='{.metadata.uid}')
          
          cat << EOF > /tmp/kubeconfig
          apiVersion: v1
          kind: Config
          clusters:
          - cluster:
              certificate-authority-data: ${CA_CERT}
              server: ${APISERVER}
            name: kubernetes
          contexts:
          - context:
              cluster: kubernetes
              namespace: ${NAMESPACE}
              user: vcluster-admin
            name: current
          current-context: current
          users:
          - name: vcluster-admin
            user:
              token: ${TOKEN}
          EOF
          
          cat << EOF > /tmp/secret.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: vcluster-kubeconfig
            annotations:
              argocd.argoproj.io/tracking-id: kubeconfig-generator
            ownerReferences:
            - apiVersion: batch/v1
              kind: Job
              name: kubeconfig-generator
              uid: ${JOB_UID}
          data:
            kubeconfig: $(cat /tmp/kubeconfig | base64 -w 0)
          EOF
          
          kubectl apply -f /tmp/secret.yaml
          
          if kubectl get secret vcluster-kubeconfig &> /dev/null; then
            echo "Successfully generated and stored kubeconfig"
            exit 0
          else
            echo "Failed to create secret"
            exit 1
          fi
      restartPolicy: OnFailure
