---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcluster-admin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vcluster-admin-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vcluster-admin-rolebinding
subjects:
- kind: ServiceAccount
  name: vcluster-admin
  namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: vcluster-admin-role
  apiGroup: rbac.authorization.k8s.io
