apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      initContainers:
      - name: init-db
        image: flyway/flyway:9
        command: ["flyway"]
        args:
        - "-url=jdbc:sqlserver://${DATABASE_HOST}:1433;databaseName=${DATABASE_NAME}"
        - "-user=$(DATABASE_USER)"
        - "-password=testing"
        - "migrate"
        env:
        - name: DATABASE_HOST
          value: "tenark-sqlserver"
        - name: DATABASE_NAME
          value: "sqldb-tenark-tenant2-inventory-db"
        # - name: DATABASE_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: inventory-db-credentials
        #       key: DATABASE_USER
        # - name: DATABASE_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: inventory-db-credentials
        #       key: DATABASE_PASSWORD
        - name: DATABASE_USER
          value: "4dm1n157r470r"
        - name: DATABASE_PASSWORD
          value: "sKaBq68#"
        resources:
          limits:
            cpu: "0.2"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        volumeMounts:
        - name: flyway-scripts
          mountPath: /flyway/sql
      volumes:
      - name: flyway-scripts
        configMap:
          name: inventory-flyway-scripts
      containers:
      - name: inventory-service
        image: inventory-service:v0.0.4
        env:
        - name: DATABASE_HOST
          value: "tenark-sqlserver"
        - name: DATABASE_NAME
          value: "sqldb-tenark-tenant2-inventory-db"
        # - name: DATABASE_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: inventory-db-credentials
        #       key: DATABASE_USER
        # - name: DATABASE_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: inventory-db-credentials
        #       key: DATABASE_PASSWORD
        - name: DATABASE_USER
          value: "4dm1n157r470r"
        - name: DATABASE_PASSWORD
          value: "sKaBq68#"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"

