apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - inventory-ingress.yaml
  - inventory-service-deployment.yaml
  - ordering-ingress.yaml
  - ordering-service-deployment.yaml
  - recommendation-ingress.yaml
  - recommendation-service-deployment.yaml