apiVersion: sql.azure.upbound.io/v1beta2
kind: MSSQLDatabase
metadata:
  name: sqldb-tenark-tenant-common
spec:
  forProvider:
    resourceGroupNameRef:
      name: rg-tenark-tenant-qa
    serverNameRef:
      name: tenark-sqlserver-qa