apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
nameSuffix: -qa
patchesStrategicMerge:
  - aks-helloworld.yaml
  - authserver-ingress.yaml
  - control-plane-ingress.yaml
  - httpapi-host-ingress.yaml
  - portal-ingress.yaml
  - recommendation-ingress.yaml
  - redis.yaml
  - resource-group.yaml
  - sql-admin-password.yaml
  - sql-database.yaml
  - sql-server.yaml
  - tenants-sass-common-apps.yaml
  - vcluster.yaml