apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  labels:
    tenark/resourcegroup: rg-tenark-tenant-dev
  name: rg-tenark-tenant
spec:
  forProvider:
    location: West Europe
    