apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-common-infra-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/zodraz/tenark-gitops-bridge'
      targetRevision: 'HEAD'
      path: 'gitops/tenants/tenant-common/overlays/dev/infra'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 5
        maxDuration: 3m0s
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-common-apps
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - repo_path: kubernetes/Tenark.AuthServer
        app: authserver
      - repo_path: kubernetes/Tenark.DbMigrator
        app: dbmigrator
      - repo_path: kubernetes/Tenark.HttpApi.Host
        app: httpapi
      - repo_path: kubernetes/Tenark.Web.ControlPlane
        app: controlplane
      - repo_path: kubernetes/Tenark.Web.Portal
        app: portal
  - clusters:
    selector:
      matchLabels:
        environment: control-plane
  template:
    metadata:
      name: tenant-common-apps-{{.app}}
    spec:
      project: default
      source:
        repoURL: 'https://github.com/zodraz/tenark-webs.git'
        targetRevision: 'HEAD'
        path: '{{.repo_path}}/overlays/dev'
      destination:
        name: 'tenant-common-dev'
        namespace: default
      syncPolicy:
        retry:
          limit: 10
        automated: {}
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-common-ingress-services-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/zodraz/tenark-gitops-bridge'
      targetRevision: 'HEAD'
      path: 'gitops/tenants/tenant-common/overlays/dev/ingress'
  destination:
    name: 'tenant-common-dev'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 5
        maxDuration: 3m0s