apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-common-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      source:
        path: '{{.repo_path}}/overlays/dev'