apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -dev
patches: 
  - path: tenant-sass-services.yaml
    target:
      kind: ApplicationSet
      name: tenant-sass-services