apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ordering-ingress
spec:
  rules:
  - host: ordering.tenant2.dev.tenark.com
  tls:
  - hosts:
    - ordering.tenant2.dev.tenark.com
    secretName: keyvault-ordering-ingress-dev