apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recommendation-ingress
spec:
  rules:
  - host: recommendation.tenant2.dev.tenark.com
  tls:
  - hosts:
    - recommendation.tenant2.dev.tenark.com
    secretName: keyvault-recommendation-ingress-dev