apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authserver-ingress
spec:
  rules:
  - host: qa.tenark.com
  tls:
  - hosts:
    - qa.tenark.com
    secretName: keyvault-authserver-ingress-dev