apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/ingress-services
nameSuffix: -dev
patches: 
  - path: inventory-ingress.yaml
    target:
      kind: Ingress
      name: inventory-ingress
  - path: inventory-service-deployment.yaml
    target:
      kind: Deployment
      name: inventory-service
  - path: ordering-ingress.yaml
    target:
      kind: Ingress
      name: ordering-ingress
  - path: ordering-service-deployment.yaml
    target:
      kind: Deployment
      name: ordering-service
  - path: recommendation-ingress.yaml
    target:
      kind: Ingress
      name: recommendation-ingress
  - path: recommendation-service-deployment.yaml
    target:
      kind: Deployment
      name: recommendation-service