apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-spring-boot
  namespace: argocd
spec:
  generators:
  - clusters: {} # (1)
  template:
    metadata:
      name: '{{name}}-sample-spring-bootv3' # (2)
    spec:
      project: default
      source: # (3)
        repoURL: https://github.com/zodraz/tenark-gitops-bridge
        targetRevision: HEAD
        path: gitops/apps/sample-spring-kotlin
      destination:
        server: '{{server}}' # (4)
        namespace: default # (5)
      syncPolicy: # (6)
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true