apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant3-vcluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    clusterName: tenant3
spec:
  project: default
  destination:
    namespace: tenant3
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.loft.sh'
    targetRevision: 0.25.0
    chart: vcluster
    helm:
      releaseName: tenant3
      values: |
        controlPlane:
          ingress:
            enabled: true
            host: tenant3.tenark.com
            spec:
              ingressClassName: nginx
          proxy:
            extraSANs:
            - tenant3.tenark.com
            - tenant3
            - tenant3.tenant3
            - tenant3.tenant3.svc
            - tenant3.tenant3.svc.cluster.local
        sync:
          fromHost:
            ingressClasses:
              enabled: true
          toHost:
            ingresses:
              enabled: true
        policies:
          resourceQuota:
            enabled: true
            quota:
              cpu: "3"
              memory: 3Gi
              pods: "10"
  sources: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true