---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-helloworld
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/zodraz/tenark-gitops-bridge'
      targetRevision: 'HEAD'
      path: 'gitops/apps/aks-helloworld'
  
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 5
        maxDuration: 3m0s

