# composition-azuresqlelasticdatabase.yaml (Corrected for forEach variable context)
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azuresqlelasticdatabase-composition
  labels:
    provider: azure
    service: sql
spec:
  compositeTypeRef:
    apiVersion: azure.example.org/v1alpha1
    kind: XAzureSQLElasticDatabase
  resources:
    # ... (ResourceGroup, SQLServer, ElasticPool sections remain unchanged)

    # 4. Create Azure SQL Databases within the Elastic Pool
    - name: sqldatabases
      base:
        apiVersion: sql.azure.upbound.io/v1beta1
        kind: MSSQLDatabase
        spec:
          forProvider:
            collation: SQL_Latin1_General_CP1_CI_AS # Default collation
          writeConnectionSecretToRef:
            namespace: crossplane-system # Or a dedicated secrets namespace
      patches:
        - fromFieldPath: spec.parameters.resourceGroupName
          toFieldPath: spec.forProvider.resourceGroupNameRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-rg"
        - fromFieldPath: spec.parameters.serverName
          toFieldPath: spec.forProvider.serverNameRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name # The XR's name (e.g., "my-app-db-cluster") is the FIRST input to the string transform
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          transforms:
            - type: string
              string:
                fmt: "%s-%s" # Expects two strings: XR name, then database name
                variables:
                  - fromFieldPath: name # <-- CRITICAL CHANGE: Reference 'name' of the current database item directly
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name # The XR's name (e.g., "my-app-db-cluster") is the FIRST input to the string transform
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-%s" # Expects two strings: XR name, then database name
                variables:
                  - fromFieldPath: name # <-- CRITICAL CHANGE: Reference 'name' of the current database item directly
        - fromFieldPath: spec.parameters.databases[name] # This is to directly set the actual Azure DB name
          toFieldPath: spec.forProvider.name
        - fromFieldPath: spec.parameters.serverName
          toFieldPath: spec.forProvider.elasticPoolIdRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-pool"
        - fromFieldPath: spec.parameters.databases[collation]
          toFieldPath: spec.forProvider.collation
          policy:
            fromFieldPath: Optional
      forEach: spec.parameters.databases