apiVersion: azure.example.org/v1alpha1
kind: XAzureSQLElasticDatabase
metadata:
  name: my-app-db-cluster
  namespace: default # Or your desired namespace for the XR and secrets
spec:
  parameters:
    location: WestUS
    resourceGroupName: my-app-rg # This will create 'my-app-rg'
    serverName: my-app-sqlserver # This will create 'my-app-sqlserver'
    administratorLogin: adminuser
    administratorLoginPasswordSecretRef:
      name: my-app-sql-password
      key: password
    namespace: default # Namespace for connection secrets

    # Define the SKU parameters for the Elastic Pool
    elasticPoolSku:
      name: GP_Gen5       # e.g., 'GP_Gen5', 'BC_Gen5', 'StandardPool'
      tier: GeneralPurpose # e.g., 'GeneralPurpose', 'BusinessCritical', 'Standard'
      capacity: 50        # e.g., 50 (for vCores), 100 (for DTUs)
      family: Gen5        # (Optional, if your SKU requires it)
      size: "100"         # (Optional, if your SKU requires it)

    # Define the perDatabaseSettings for the Elastic Pool (this is an array)
    perDatabaseSettings:
      - maxCapacity: 1
        minCapacity: 0.1

    # Define the databases to be created in the Elastic Pool (this is an array)
    databases:
      - name: myappdb1
        collation: SQL_Latin1_General_CP1_CI_AS # Optional
      - name: myappdb2
        collation: SQL_Latin1_General_CP1_CI_AS # Optional
      # Add more database entries as needed