# apiVersion: azure.upbound.io/v1beta1
# kind: ProviderConfig
# metadata:
#   name: azure-hotmail
#   namespace: crossplane-system
# spec:
#   credentials:
#     source: Secret
#     secretRef:
#       namespace: crossplane-system
#       name: azure-hotmail-credentials
#       key: credentials