apiVersion: azure.tenark.com/v1alpha1
kind: XAzureSQLElasticDatabase
metadata:
  name: tenark-sql-elastic-db-cluster
  namespace: workload
spec:
  parameters:
    location: WestEurope
    resourceGroupName: tenark-infra-common
    serverName: tenark-sqlserver-common
    administratorLogin: sqladmin
    administratorLoginPasswordSecretRef:
      name: sql-admin-password
      key: password
    namespace: workload # Namespace for connection secrets

    # SKU parameters for the Elastic Pool
    elasticPoolSku:
      name: GP_Gen5       # e.g., 'GP_Gen5', 'BC_Gen5', 'StandardPool'
      tier: GeneralPurpose # e.g., 'GeneralPurpose', 'BusinessCritical', 'Standard'
      capacity: 2        # e.g., 50 (for vCores), 100 (for DTUs)
      family: Gen5        # (Optional, if your SKU requires it)
      size: "100"         # (Optional, if your SKU requires it)

    # perDatabaseSettings for the Elastic Pool
    perDatabaseSettings:
      - maxCapacity: 1
        minCapacity: 0.1

    # databases to be created in the Elastic Pool (this is an array)
    databases:
      - name: tenant-common
        collation: SQL_Latin1_General_CP1_CI_AS # Optional
      - name: tenant2
        collation: SQL_Latin1_General_CP1_CI_AS # Optional