apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - authserver-ingress.yaml
  - controlplane-ingress.yaml
  - httpapi-host-ingress.yaml
  - portal-ingress.yaml
  # - tenant-common-apps.yaml