apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-common-apps
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - repo_path: kubernetes/Tenark.AuthServer
        app: authserver
      - repo_path: kubernetes/Tenark.DbMigrator
        app: dbmigrator
      - repo_path: kubernetes/Tenark.HttpApi.Host
        app: httpapi
      - repo_path: kubernetes/Tenark.Web.ControlPlane
        app: controlplane
      - repo_path: kubernetes/Tenark.Web.Portal
        app: portal
  - clusters:
    selector:
      matchLabels:
        environment: control-plane
  template:
    metadata:
      name: tenant-common-apps-{{.app}}
    spec:
      project: default
      source:
        repoURL: 'https://github.com/zodraz/tenark-webs.git'
        targetRevision: 'HEAD'
        path: '{{.repo_path}}'
      destination:
        name: '{{name}}'
        namespace: default
      syncPolicy:
        retry:
          limit: 10
        automated: {}
        syncOptions:
          - CreateNamespace=true