apiVersion: v1
kind: Service
metadata:
  name: vcluster-loadbalancer
spec:
  selector:
    app: vcluster
    release: vcluster-dev
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: LoadBalancer