apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/ingress
nameSuffix: -dev
patches: 
  - path: inventory-ingress.yaml
    target:
      kind: Ingress
      name: inventory-ingress
  - path: ordering-ingress.yaml
    target:
      kind: Ingress
      name: ordering-ingress
  - path: recommendation-ingress.yaml
    target:
      kind: Ingress
      name: recommendation-ingress