apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -prod
patches: 
  - path: authserver-ingress.yaml
    target:
      kind: Ingress
      name: authserver-ingress
  - path: controlplane-ingress.yaml
    target:
      kind: Ingress
      name: controlplane-ingress
  - path: httpapi-host-ingress.yaml
    target:
      kind: Ingress
      name: httpapi-host-ingress
  - path: portal-ingress.yaml
    target:
      kind: Ingress
      name: portal-ingress