apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpapi-host-ingress
spec:
  rules:
  - host: qa.tenark.com
  tls:
  - hosts:
    - qa.tenark.com
    secretName: keyvault-httpapi-host-ingress-dev