apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
nameSuffix: -qa
patchesStrategicMerge:
  - inventory-ingress.yaml
  - ordering-ingress.yaml
  - recommendation-ingress.yaml
  - redis.yaml
  - sql-database.yaml.yaml
  - tenant-sass-services.yaml
  - vcluster.yaml

