apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
spec:
  template:
    spec:
      initContainers:
      - name: init-db
        env:
        - name: DATABASE_HOST
          value: "tenark-sqlserver-qa"
        - name: DATABASE_NAME
          value: "recommendation-db-tenant2"
      containers:
      - name: recommendation-service
        env:
        - name: DATABASE_HOST
          value: "tenark-sqlserver-qa"
        - name: DATABASE_NAME
          value: "recommendation-db-tenant2"