apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant2-vcluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    clusterName: tenant2-qa
spec:
  project: default
  destination:
    namespace: tenant2
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.loft.sh'
    targetRevision: 0.25.0
    chart: vcluster
    helm:
      releaseName: tenant2
      values: |
        controlPlane:
          ingress:
            enabled: true
            host: tenant2-qa.tenark.com
            spec:
              ingressClassName: nginx
          proxy:
            extraSANs:
            - tenant2-qa.tenark.com
            - tenant2-qa
            - tenant2-qa.tenant2
            - tenant2-qa.tenant2.svc
            - tenant2-qa.tenant2.svc.cluster.local
        sync:
          fromHost:
            ingressClasses:
              enabled: true
          toHost:
            ingresses:
              enabled: true
  sources: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true