apiVersion: sql.azure.upbound.io/v1beta2
kind: MSSQLServer
metadata:
  labels:
    tenark/sqlserver: tenark-sqlserver-dev
  name: tenark-sqlserver
spec:
  forProvider:
    administratorLoginPasswordSecretRef:
      key: password
      name: sql-admin-password-dev
      namespace: default
    resourceGroupNameSelector:
      matchLabels:
        tenark/resourcegroup: rg-tenark-tenant-dev