provider:
  enabled: true
  metadata:
    annotations: {}
    labels:
      app.kubernetes.io/managed-by: Helm
      azure.workload.identity/use: "true"
  package:
    registry: xpkg.upbound.io/upbound
    version: v1.11.0

deploymentRuntimeConfig:
  enabled: true

providers:
- network
- compute
- storage
- authorization
- containerservice
- containerregistry
- keyvault
- operationalinsights
- insights
- managedidentity
- resources
- cache
- sql