apiVersion: containerservice.azure.upbound.io/v1beta2
kind: KubernetesCluster
metadata:
  annotations:
    meta.upbound.io/example-id: containerservice/v1beta2/kubernetescluster
  labels:
    testing.upbound.io/example-name: example
  name: example-kc-with-uai
spec:
  forProvider:
    apiServerAccessProfile:
      authorizedIpRanges:
        - 192.168.1.0/24
    defaultNodePool:
      name: default
      nodeCount: 1
      upgradeSettings:
        maxSurge: 10%
      vmSize: Standard_D2_v2
    dnsPrefix: exampleaks1
    identity:
      identityIdsSelector:
        matchLabels:
          testing.upbound.io/example-name: exmple-managedidentity
      type: UserAssigned
    location: North Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example-containerservice
    tags:
      Environment: Production