apiVersion: eventgrid.azure.upbound.io/v1beta2
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: eventgrid/v1beta2/topic
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: topic-rg
    tags:
      environment: Production
---
apiVersion: eventgrid.azure.upbound.io/v1beta2
kind: EventSubscription
metadata:
  annotations:
    meta.upbound.io/example-id: eventgrid/v1beta2/eventsubscription
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example-aees
    scopeSelector:
      matchLabels:
        testing.upbound.io/example-name: eventsubscription-rg
    storageQueueEndpoint:
      queueNameSelector:
        matchLabels:
          testing.upbound.io/example-name: eventsubscriptionqueue
      storageAccountIdSelector:
        matchLabels:
          testing.upbound.io/example-name: eventgridstoracc