apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventory-ingress
spec:
  rules:
  - host: inventory.tenant2.prod.tenark.com
  tls:
  - hosts:
    - inventory.tenant2.prod.tenark.com
    secretName: keyvault-inventory-ingress-prod