apiVersion: sql.azure.upbound.io/v1beta2
kind: MSSQLServer
metadata:
  name: tenark-sqlserver
spec:
  forProvider:
    administratorLogin: 4dm1n157r470r
    administratorLoginPasswordSecretRef:
      key: password
      name: sql-admin-password
      namespace: default
    location: West Europe
    resourceGroupNameRef:
      name: rg-tenark-tenant
    version: "12.0"