apiVersion: sql.azure.upbound.io/v1beta2
kind: MSSQLDatabase
metadata:
  name: sqldb-tenark-tenant-common
spec:
  forProvider:
    resourceGroupNameRef:
      name: rg-tenark-tenant
    serverNameRef:
      name: tenark-sqlserver
    name: tenant-common
    collation: SQL_Latin1_General_CP1_CI_AS
    licenseType: LicenseIncluded
    maxSizeGb: 1
    skuName: S0
    tags:
      tenant: tenant-common