apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
nameSuffix: -prod
patchesStrategicMerge:
  - authserver-ingress.yaml
  - controlplane-ingress.yaml
  - httpapi-host-ingress.yaml
  - portal-ingress.yaml
  - redis.yaml
  - resource-group.yaml
  - sql-admin-password.yaml
  - sql-database.yaml
  - sql-server.yaml
  - tenants-sass-common-apps.yaml
  - vcluster.yaml