apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-common-vcluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    clusterName: tenant-common-qa
spec:
  project: default
  destination:
    namespace: tenant-common-qa
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.loft.sh'
    targetRevision: 0.25.0
    chart: vcluster
    helm:
      releaseName: tenant-common-qa
      values: |
        controlPlane:
          ingress:
            enabled: true
            host: tenant-common-qa.tenark.com
            spec:
              ingressClassName: nginx
          proxy:
            extraSANs:
            - tenant-common-qa
            - tenant-common-qa.tenant-common-qa
            - tenant-common-qa.tenant-common-qa.svc
            - tenant-common-qa.tenant-common-qa.svc.cluster.local
        sync:
          fromHost:
            ingressClasses:
              enabled: true
          toHost:
            ingresses:
              enabled: true
  sources: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true