apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/deployments
nameSuffix: -dev
patches: 
  - path: inventory-service-deployment.yaml
    target:
      kind: Deployment
      name: inventory-service
  - path: ordering-service-deployment.yaml
    target:
      kind: Deployment
      name: ordering-service
  - path: recommendation-service-deployment.yaml
    target:
      kind: Deployment
      name: recommendation-service