apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: controlplane-ingress
spec:
  rules:
  - host: tenark.com
  tls:
  - hosts:
    - tenark.com
    secretName: keyvault-controlplane-ingress-dev