apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/infra
nameSuffix: -dev
patches: 
  - path: redis.yaml
    target:
      kind: RedisCache
      name: redis-tenark-tenant2
  - path: resource-group.yaml
    target:
      kind: ResourceGroup
      name: rg-tenark-tenant2
  - path: sql-database-inventory.yaml
    target:
      kind: MSSQLDatabase
      name: sqldb-tenark-tenant2-inventory-db
  - path: sql-database-ordering.yaml
    target:
      kind: MSSQLDatabase
      name: sqldb-tenark-tenant2-ordering-db
  - path: sql-database-recommendation.yaml
    target:
      kind: MSSQLDatabase
      name: sqldb-tenark-tenant2-recommendation-db
  - path: vcluster.yaml
    target:
      kind: Application
      name: tenant2-vcluster