apiVersion: sql.azure.upbound.io/v1beta2
kind: MSSQLDatabase
metadata:
  labels:
    tenark/sqlserverdatabase: tenark-sqlserver-dev
  name: sqldb-tenark-tenant2-inventory-db
spec:
  forProvider:
    serverIdSelector:
      matchLabels:
        tenark/sqlserver: tenark-sqlserver-dev